"""empty message

Revision ID: 1c319873159e
Revises: d592ef8c1954
Create Date: 2025-08-13 17:52:26.089204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c319873159e'
down_revision = 'd592ef8c1954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
