"""empty message

Revision ID: 63121721063f
Revises: 0763d677d453
Create Date: 2025-07-20 19:26:42.876774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63121721063f'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
