"""empty message

Revision ID: 93e11c0e5f9b
Revises: 
Create Date: 2025-08-27 23:50:31.702107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e11c0e5f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('secret_question', sa.String(length=100), nullable=False),
    sa.Column('question_answer', sa.String(length=100), nullable=False),
    sa.Column('chest_pr', sa.Integer(), nullable=True),
    sa.Column('back_pr', sa.Integer(), nullable=True),
    sa.Column('legs_pr', sa.Integer(), nullable=True),
    sa.Column('arms_pr', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=True),
    sa.Column('proteinas', sa.Integer(), nullable=True),
    sa.Column('entrenamientos', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_id', sa.Integer(), nullable=False),
    sa.Column('entrenamientos', sa.Boolean(), nullable=True),
    sa.Column('ejercicio', sa.String(length=20), nullable=False),
    sa.Column('sueño', sa.String(length=20), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=False),
    sa.Column('proteinas', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.String(length=50), nullable=False),
    sa.Column('lunch', sa.String(length=50), nullable=False),
    sa.Column('dinner', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['daily_id'], ['daily.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit')
    op.drop_table('goals')
    op.drop_table('daily')
    op.drop_table('user')
    # ### end Alembic commands ###
