"""empty message

Revision ID: cc9aad2af11d
Revises: 
Create Date: 2025-08-05 15:59:08.304796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9aad2af11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('secret_question', sa.String(length=100), nullable=False),
    sa.Column('question_answer', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_id', sa.Integer(), nullable=False),
    sa.Column('entreno', sa.Boolean(), nullable=True),
    sa.Column('ejercicio', sa.String(length=20), nullable=False),
    sa.Column('sueño', sa.String(length=20), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=False),
    sa.Column('proteinas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_id'], ['daily.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit')
    op.drop_table('daily')
    op.drop_table('user')
    # ### end Alembic commands ###
